/**
 * Service PortalLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import {
  AddCompanyTypeRequest,
  addCompanyTypeRequestSchema,
} from '../models/addCompanyTypeRequest';
import {
  UpdateCompanyTypeRequest,
  updateCompanyTypeRequestSchema,
} from '../models/updateCompanyTypeRequest';
import { BaseController } from './baseController';

export class CompanyTypeADMINController extends BaseController {
  /**
   * @return Response from the API call
   */
  async companyTypeList(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/companyType');
    req.baseUrl('Server 2');
    req.authenticate(false);
    return req.call(requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async addCompanyType(
    body: AddCompanyTypeRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/companyType');
    req.baseUrl('Server 2');
    const mapped = req.prepareArgs({
      body: [body, addCompanyTypeRequestSchema],
    });
    req.json(mapped.body);
    req.authenticate([{ bearer: true }]);
    return req.call(requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async updateCompanyType(
    body: UpdateCompanyTypeRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest(
      'PATCH',
      '/companyType/66713dc40b7c3742bb1cfb06'
    );
    req.baseUrl('Server 2');
    const mapped = req.prepareArgs({
      body: [body, updateCompanyTypeRequestSchema],
    });
    req.json(mapped.body);
    req.authenticate([{ bearer: true }]);
    return req.call(requestOptions);
  }

  /**
   * @return Response from the API call
   */
  async addDocumentListCompanyType(
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('GET', '/companyType/doc');
    req.baseUrl('Server 2');
    req.authenticate([]);
    return req.call(requestOptions);
  }
}
