/**
 * Service PortalLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { ApiResponse, RequestOptions } from '../core';
import { LoginRequest1, loginRequest1Schema } from '../models/loginRequest1';
import {
  VerifySupplierOTPRequest,
  verifySupplierOTPRequestSchema,
} from '../models/verifySupplierOTPRequest';
import { BaseController } from './baseController';

export class OrganisationLoginController extends BaseController {
  /**
   * @param body
   * @return Response from the API call
   */
  async login(
    body: LoginRequest1,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest('POST', '/authentication/supplier');
    req.baseUrl('Server 2');
    const mapped = req.prepareArgs({ body: [body, loginRequest1Schema] });
    req.json(mapped.body);
    req.authenticate([]);
    return req.call(requestOptions);
  }

  /**
   * @param body
   * @return Response from the API call
   */
  async verifySupplierOTP(
    body: VerifySupplierOTPRequest,
    requestOptions?: RequestOptions
  ): Promise<ApiResponse<void>> {
    const req = this.createRequest(
      'POST',
      '/authentication/supplier/verifyOtp'
    );
    req.baseUrl('Server 2');
    const mapped = req.prepareArgs({
      body: [body, verifySupplierOTPRequestSchema],
    });
    req.json(mapped.body);
    req.authenticate([]);
    return req.call(requestOptions);
  }
}
