/**
 * Service PortalLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, Schema, string } from '../schema';

export interface AddNewDocumentRequest {
  documentName: string;
  companyId: number;
}

export const addNewDocumentRequestSchema: Schema<AddNewDocumentRequest> = object(
  {
    documentName: ['documentName', string()],
    companyId: ['companyId', number()],
  }
);
