/**
 * Service PortalLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface DeleteRequest {
  id: string;
}

export const deleteRequestSchema: Schema<DeleteRequest> = object({
  id: ['id', string()],
});
