/**
 * Service PortalLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface GenerateEmailOTP2Request {
  id: string;
  email: string;
}

export const generateEmailOTP2RequestSchema: Schema<GenerateEmailOTP2Request> = object(
  { id: ['id', string()], email: ['email', string()] }
);
