/**
 * Service PortalLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface LoginRequest {
  email: string;
  password: string;
}

export const loginRequestSchema: Schema<LoginRequest> = object({
  email: ['email', string()],
  password: ['password', string()],
});
