/**
 * Service PortalLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface LoginRequest1 {
  email: string;
}

export const loginRequest1Schema: Schema<LoginRequest1> = object({
  email: ['email', string()],
});
