/**
 * Service PortalLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface UpdateCompanyTypeRequest {
  name: string;
  active: string;
}

export const updateCompanyTypeRequestSchema: Schema<UpdateCompanyTypeRequest> = object(
  { name: ['name', string()], active: ['active', string()] }
);
