/**
 * Service PortalLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface VerifyOtp3Request {
  id: string;
  otp: string;
}

export const verifyOtp3RequestSchema: Schema<VerifyOtp3Request> = object({
  id: ['id', string()],
  otp: ['otp', string()],
});
