/**
 * Service PortalLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { object, Schema, string } from '../schema';

export interface VerifySupplierOTPRequest {
  id: string;
  otp: string;
}

export const verifySupplierOTPRequestSchema: Schema<VerifySupplierOTPRequest> = object(
  { id: ['id', string()], otp: ['otp', string()] }
);
